version: '3.7'

services:
  server:
    container_name: food_delivery_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
